version: "3"

name: saas-starter-kit

services:
  payload:
    image: node:18-alpine
    container_name: saas-starter-kit-payload
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "yarn install && yarn dev"
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - DATABASE_URI=postgres://payload:payload@postgres:5432/payload
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: saas-starter-kit-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=payload
      - POSTGRES_PASSWORD=payload
      - POSTGRES_DB=payload
    volumes:
      - saas_starter_kit_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U payload"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  saas_starter_kit_postgres_data:
  node_modules:
